[[section-introduction-and-goals]]
===	Introduktion

****
Das System ist ein interaktives Videospiel, das die Zielgruppe über den Einfluss von Mikroplastik auf das Grundwasser und dessen Umweltverschmutzung aufklärt.

Durch die Simulation von Materialien und deren Wechselwirkungen mit Wasser ermöglicht das Spiel ein tieferes Verständnis der ökologischen Konsequenzen von Mikroplastik.

Nutzer*innen können verschiedene Objekte auswählen, die durch ein Scanning-Feature analysiert werden, um deren Materialeigenschaften und Auswirkungen auf die Schwierigkeit der Simulation anzupassen.

Das Kernziel ist es, durch spielerische Interaktionen die Bewusstseinsbildung über Umweltverschmutzung und nachhaltige Materialwahl zu fördern.
****

=== Qualitätsziele

[cols="1,2,9" options="header"]
|===
|ID |Name |Description
| Q01 | Performance | The game steps should not take more than 16 milliseconds to ensure that game steps do not overlap and feel smooth

The Window should not freeze if the main controller is in a loop for an extended period of time
| Q02 | Usability | A user unfamiliar with the system can use it without many difficulties
| Q03 | Reliability | All saved data can be retrieved with little to no corruption being present

The code inside long functions should be commented periodically to explain what a section does
|Q04|Maintainability| The final product is capable of being modified without extraneous effort
|Q05|Accessibility|The project can run on a RaspberryPi 5 without an internet connection
|===

=== Stakeholders

[cols="1,2,6" options="header"]
|===
| Role | Kontakt | Erwartungen
| Client | Primeo | Functional and maintainable system that they can cost-effectively implement
| Product Owner | Andreas Vogt | A product that fulfills both the clients and users needs
| Users | --- | A functional and robust System
| FHNW | --- | That all Stakeholders are satisfied by the end result
|===
