[[section-introduction-and-goals]]
==	Einführung und Ziele

[role="arc42help"]
****
The Goal of this project is
****

=== Aufgabenstellung

[role="arc42help"]
****
.Inhalt
Kurzbeschreibung der fachlichen Aufgabenstellung, treibenden Kräfte, Extrakt (oder Abstract) der Anforderungen.
Verweis auf (hoffentlich vorliegende) Anforderungsdokumente (mit Versionsbezeichnungen und Ablageorten).

.Motivation
Aus Sicht der späteren Nutzung ist die Unterstützung einer fachlichen Aufgabe oder Verbesserung der Qualität der eigentliche Beweggrund, ein neues System zu schaffen oder ein bestehendes zu modifizieren.

.Form
Kurze textuelle Beschreibung, eventuell in tabellarischer Use-Case Form.
Sofern vorhanden, sollte die Aufgabenstellung Verweise auf die entsprechenden Anforderungsdokumente enthalten.

Halten Sie diese Auszüge so knapp wie möglich und wägen Sie Lesbarkeit und Redundanzfreiheit gegeneinander ab.


.Weiterführende Informationen

Siehe https://docs.arc42.org/section-1/[Anforderungen und Ziele] in der online-Dokumentation (auf Englisch!).

****

****
h
****

=== Qualitätsziele

[cols="1,1,2" options="header"]
|===
|ID |Name |Description
| _Q01_ | _Performance_ | _The game steps should not take more than 16 milliseconds to ensure that game steps do not overlap and feel smooth._

_The Window should not freeze if the main controller is in a loop for an extended period of time._
| _Q02_ | _Modularity_ | _The code should be modular and reusable in other parts of the codebase._
| _Q03_ | _Readability_ | _Each function should have a short description before it explaining what it does._

_The code inside long functions should be commented periodically to explain what a section does._
|===

=== Stakeholders

[cols="1,1,2" options="header"]
|===
| Role | Contact | Expectations
| _Client_ | _Primeo_ | _Functional and maintainable system that they can cost-effectively implement._
| _Product Owner_ | _Andreas Vogt_ | _A product that fulfills both the clients and users needs._
| _Users_ | _---_ | _A functional and robust System._
| _FHNW_ | _---_ | _That all Stakeholders are satisfied by the end result._
|===
